import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full max-w-[576px] mx-auto">
      <body className="grid grid-cols-5 gap-[16px]">
        {children}
      </body>
    </html>
  );
}
