import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full max-w-[576px] mx-auto">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/jak6kpc.css"></link>
      </head>
      <body className="grid grid-cols-5 gap-4 mx-4">
        {children}
      </body>
    </html>
  );
}
